services:
  youtube-extrator-web:
    build: .
    container_name: youtube-extrator-web
    environment:
      APP_MODE: web
      PORT: 5000
      GUNICORN_WORKERS: 2
      GUNICORN_THREADS: 4
      GUNICORN_TIMEOUT: 180
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped

  youtube-extrator-bot:
    build: .
    container_name: youtube-extrator-bot
    environment:
      APP_MODE: telegram
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
    profiles:
      - telegram
